// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package api_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressGetOptions struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Bagid                string   `protobuf:"bytes,3,opt,name=bagid" json:"bagid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressGetOptions) Reset()         { *m = AddressGetOptions{} }
func (m *AddressGetOptions) String() string { return proto.CompactTextString(m) }
func (*AddressGetOptions) ProtoMessage()    {}
func (*AddressGetOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{0}
}
func (m *AddressGetOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressGetOptions.Unmarshal(m, b)
}
func (m *AddressGetOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressGetOptions.Marshal(b, m, deterministic)
}
func (dst *AddressGetOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressGetOptions.Merge(dst, src)
}
func (m *AddressGetOptions) XXX_Size() int {
	return xxx_messageInfo_AddressGetOptions.Size(m)
}
func (m *AddressGetOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressGetOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AddressGetOptions proto.InternalMessageInfo

func (m *AddressGetOptions) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddressGetOptions) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AddressGetOptions) GetBagid() string {
	if m != nil {
		return m.Bagid
	}
	return ""
}

type AddressGetByPathOptions struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressGetByPathOptions) Reset()         { *m = AddressGetByPathOptions{} }
func (m *AddressGetByPathOptions) String() string { return proto.CompactTextString(m) }
func (*AddressGetByPathOptions) ProtoMessage()    {}
func (*AddressGetByPathOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{1}
}
func (m *AddressGetByPathOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressGetByPathOptions.Unmarshal(m, b)
}
func (m *AddressGetByPathOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressGetByPathOptions.Marshal(b, m, deterministic)
}
func (dst *AddressGetByPathOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressGetByPathOptions.Merge(dst, src)
}
func (m *AddressGetByPathOptions) XXX_Size() int {
	return xxx_messageInfo_AddressGetByPathOptions.Size(m)
}
func (m *AddressGetByPathOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressGetByPathOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AddressGetByPathOptions proto.InternalMessageInfo

func (m *AddressGetByPathOptions) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type AddressGetMultiOptions struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressGetMultiOptions) Reset()         { *m = AddressGetMultiOptions{} }
func (m *AddressGetMultiOptions) String() string { return proto.CompactTextString(m) }
func (*AddressGetMultiOptions) ProtoMessage()    {}
func (*AddressGetMultiOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{2}
}
func (m *AddressGetMultiOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressGetMultiOptions.Unmarshal(m, b)
}
func (m *AddressGetMultiOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressGetMultiOptions.Marshal(b, m, deterministic)
}
func (dst *AddressGetMultiOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressGetMultiOptions.Merge(dst, src)
}
func (m *AddressGetMultiOptions) XXX_Size() int {
	return xxx_messageInfo_AddressGetMultiOptions.Size(m)
}
func (m *AddressGetMultiOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressGetMultiOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AddressGetMultiOptions proto.InternalMessageInfo

func (m *AddressGetMultiOptions) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type AddressListOptions struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddressListOptions) Reset()         { *m = AddressListOptions{} }
func (m *AddressListOptions) String() string { return proto.CompactTextString(m) }
func (*AddressListOptions) ProtoMessage()    {}
func (*AddressListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{3}
}
func (m *AddressListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressListOptions.Unmarshal(m, b)
}
func (m *AddressListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressListOptions.Marshal(b, m, deterministic)
}
func (dst *AddressListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressListOptions.Merge(dst, src)
}
func (m *AddressListOptions) XXX_Size() int {
	return xxx_messageInfo_AddressListOptions.Size(m)
}
func (m *AddressListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AddressListOptions proto.InternalMessageInfo

func (m *AddressListOptions) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Address struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Bagid                string   `protobuf:"bytes,3,opt,name=bagid" json:"bagid,omitempty"`
	Legacy               *Legacy  `protobuf:"bytes,4,opt,name=legacy" json:"legacy,omitempty"`
	Suggest              []string `protobuf:"bytes,5,rep,name=suggest" json:"suggest,omitempty"`
	Forsale              bool     `protobuf:"varint,6,opt,name=forsale" json:"forsale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{4}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Address) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Address) GetBagid() string {
	if m != nil {
		return m.Bagid
	}
	return ""
}

func (m *Address) GetLegacy() *Legacy {
	if m != nil {
		return m.Legacy
	}
	return nil
}

func (m *Address) GetSuggest() []string {
	if m != nil {
		return m.Suggest
	}
	return nil
}

func (m *Address) GetForsale() bool {
	if m != nil {
		return m.Forsale
	}
	return false
}

type Addresses struct {
	Addresses            []*Address  `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Addresses) Reset()         { *m = Addresses{} }
func (m *Addresses) String() string { return proto.CompactTextString(m) }
func (*Addresses) ProtoMessage()    {}
func (*Addresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_address_25e0d8e63639ee4d, []int{5}
}
func (m *Addresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addresses.Unmarshal(m, b)
}
func (m *Addresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addresses.Marshal(b, m, deterministic)
}
func (dst *Addresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addresses.Merge(dst, src)
}
func (m *Addresses) XXX_Size() int {
	return xxx_messageInfo_Addresses.Size(m)
}
func (m *Addresses) XXX_DiscardUnknown() {
	xxx_messageInfo_Addresses.DiscardUnknown(m)
}

var xxx_messageInfo_Addresses proto.InternalMessageInfo

func (m *Addresses) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Addresses) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*AddressGetOptions)(nil), "api_v1.AddressGetOptions")
	proto.RegisterType((*AddressGetByPathOptions)(nil), "api_v1.AddressGetByPathOptions")
	proto.RegisterType((*AddressGetMultiOptions)(nil), "api_v1.AddressGetMultiOptions")
	proto.RegisterType((*AddressListOptions)(nil), "api_v1.AddressListOptions")
	proto.RegisterType((*Address)(nil), "api_v1.Address")
	proto.RegisterType((*Addresses)(nil), "api_v1.Addresses")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressServiceClient interface {
	Get(ctx context.Context, in *AddressGetOptions, opts ...grpc.CallOption) (*Address, error)
	GetMulti(ctx context.Context, in *AddressGetMultiOptions, opts ...grpc.CallOption) (*Addresses, error)
	List(ctx context.Context, in *AddressListOptions, opts ...grpc.CallOption) (*Addresses, error)
	Update(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Address, error)
}

type addressServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressServiceClient(cc *grpc.ClientConn) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) Get(ctx context.Context, in *AddressGetOptions, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/api_v1.AddressService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) GetMulti(ctx context.Context, in *AddressGetMultiOptions, opts ...grpc.CallOption) (*Addresses, error) {
	out := new(Addresses)
	err := c.cc.Invoke(ctx, "/api_v1.AddressService/GetMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) List(ctx context.Context, in *AddressListOptions, opts ...grpc.CallOption) (*Addresses, error) {
	out := new(Addresses)
	err := c.cc.Invoke(ctx, "/api_v1.AddressService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) Update(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/api_v1.AddressService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
type AddressServiceServer interface {
	Get(context.Context, *AddressGetOptions) (*Address, error)
	GetMulti(context.Context, *AddressGetMultiOptions) (*Addresses, error)
	List(context.Context, *AddressListOptions) (*Addresses, error)
	Update(context.Context, *Address) (*Address, error)
}

func RegisterAddressServiceServer(s *grpc.Server, srv AddressServiceServer) {
	s.RegisterService(&_AddressService_serviceDesc, srv)
}

func _AddressService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_v1.AddressService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Get(ctx, req.(*AddressGetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_GetMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressGetMultiOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).GetMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_v1.AddressService/GetMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).GetMulti(ctx, req.(*AddressGetMultiOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressListOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_v1.AddressService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).List(ctx, req.(*AddressListOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_v1.AddressService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Update(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api_v1.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AddressService_Get_Handler,
		},
		{
			MethodName: "GetMulti",
			Handler:    _AddressService_GetMulti_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AddressService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AddressService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "address.proto",
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_address_25e0d8e63639ee4d) }

var fileDescriptor_address_25e0d8e63639ee4d = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x6e, 0xd4, 0x30,
	0x14, 0xc6, 0x49, 0x32, 0x4d, 0x9b, 0x57, 0x98, 0xce, 0x3c, 0x55, 0xad, 0x89, 0x2a, 0x34, 0xf2,
	0x02, 0x8d, 0x10, 0x9d, 0xa8, 0xe1, 0x04, 0xb0, 0x29, 0x42, 0xad, 0x5a, 0x05, 0xb1, 0x62, 0x81,
	0xdc, 0xc6, 0xb8, 0x96, 0x42, 0x12, 0xc5, 0xee, 0x48, 0xdd, 0x72, 0x05, 0x0e, 0xc0, 0x35, 0xb8,
	0x07, 0x57, 0xe0, 0x20, 0x28, 0x8e, 0x3d, 0x89, 0x32, 0x2c, 0x50, 0x77, 0x7e, 0xef, 0xfb, 0xf2,
	0x7b, 0x7f, 0xec, 0xc0, 0x33, 0x96, 0xe7, 0x0d, 0x57, 0x6a, 0x55, 0x37, 0x95, 0xae, 0x30, 0x64,
	0xb5, 0xfc, 0xb2, 0x3e, 0x8b, 0x9f, 0x16, 0x5c, 0xb0, 0xdb, 0x87, 0x2e, 0x1b, 0xcf, 0x6a, 0x26,
	0x64, 0xc9, 0xb4, 0xac, 0x4a, 0x9b, 0x39, 0x11, 0x55, 0x25, 0x0a, 0x9e, 0xb0, 0x5a, 0x26, 0xac,
	0x2c, 0x2b, 0x6d, 0x44, 0x4b, 0xa1, 0x97, 0x30, 0x7f, 0xdb, 0x61, 0xcf, 0xb9, 0xbe, 0xaa, 0x8d,
	0x84, 0x53, 0xf0, 0x65, 0x4e, 0xbc, 0x85, 0xb7, 0x8c, 0x32, 0x5f, 0xe6, 0x88, 0x30, 0xa9, 0x99,
	0xbe, 0x23, 0xbe, 0xc9, 0x98, 0x33, 0x1e, 0xc2, 0xce, 0x0d, 0x13, 0x32, 0x27, 0x81, 0x49, 0x76,
	0x01, 0x3d, 0x85, 0xe3, 0x1e, 0xf7, 0xee, 0xe1, 0x9a, 0xe9, 0x3b, 0x07, 0x75, 0x10, 0xaf, 0x87,
	0xd0, 0x57, 0x70, 0xd4, 0xdb, 0x2f, 0xef, 0x0b, 0x2d, 0x9d, 0x7b, 0x06, 0x81, 0xcc, 0x15, 0xf1,
	0x16, 0xc1, 0x32, 0xca, 0xda, 0x23, 0x7d, 0x0f, 0x68, 0xbd, 0x17, 0x52, 0x6d, 0x5a, 0x4d, 0x01,
	0xfa, 0x89, 0x0d, 0x7b, 0x3f, 0xc5, 0x55, 0xb7, 0x9a, 0xd5, 0xf5, 0x46, 0xc9, 0x06, 0x2e, 0xfa,
	0xd3, 0x83, 0x5d, 0x8b, 0x7a, 0xfc, 0xa8, 0xf8, 0x12, 0xc2, 0x6e, 0xf3, 0x64, 0x62, 0xaa, 0x4e,
	0x5d, 0xd5, 0x0b, 0x93, 0xcd, 0xac, 0x8a, 0x04, 0x76, 0xd5, 0xbd, 0x10, 0x5c, 0x69, 0xb2, 0x63,
	0xa6, 0x71, 0x61, 0xab, 0x7c, 0xad, 0x1a, 0xc5, 0x0a, 0x4e, 0xc2, 0x85, 0xb7, 0xdc, 0xcb, 0x5c,
	0x48, 0x4b, 0x88, 0x6c, 0x83, 0x5c, 0xe1, 0x29, 0x44, 0xcc, 0x05, 0x66, 0x21, 0xfb, 0xe9, 0x81,
	0xab, 0x65, 0x5d, 0x59, 0xef, 0x18, 0x6d, 0xc4, 0xff, 0x9f, 0x8d, 0xa4, 0xbf, 0x7c, 0x98, 0x5a,
	0xd4, 0x47, 0xde, 0xac, 0xe5, 0x2d, 0xc7, 0x0f, 0x10, 0x9c, 0x73, 0x8d, 0xcf, 0x47, 0x95, 0xfa,
	0x57, 0x12, 0x8f, 0x9b, 0xa0, 0xc7, 0xdf, 0x7f, 0xff, 0xf9, 0xe1, 0xcf, 0xf1, 0x20, 0x59, 0x9f,
	0x25, 0xb6, 0xa1, 0x44, 0x70, 0x8d, 0x9f, 0x61, 0xcf, 0xdd, 0x2f, 0xbe, 0xd8, 0x06, 0x0e, 0x2f,
	0x3e, 0x9e, 0x8f, 0x74, 0xae, 0xe8, 0x89, 0xe1, 0x1e, 0xe1, 0xe1, 0x88, 0xfb, 0xcd, 0x00, 0xaf,
	0x60, 0xd2, 0x3e, 0x08, 0x8c, 0x47, 0x1f, 0x0e, 0x5e, 0xc9, 0xbf, 0xa0, 0xc4, 0x40, 0x11, 0x67,
	0x43, 0x68, 0xd1, 0x82, 0x5e, 0x43, 0xf8, 0xa9, 0xce, 0x99, 0xe6, 0x38, 0x9e, 0x70, 0x7b, 0xe4,
	0x27, 0x37, 0xa1, 0xf9, 0x8f, 0xde, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x4b, 0xe7, 0x2c,
	0x9e, 0x03, 0x00, 0x00,
}
