// Code generated by protoc-gen-go. DO NOT EDIT.
// source: legacy.proto

package api_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Legacy struct {
	// @inject_tag: datastore:",noindex"
	Source               []byte   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty" datastore:",noindex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" datastore:"-"`
	XXX_unrecognized     []byte   `json:"-" datastore:"-"`
	XXX_sizecache        int32    `json:"-" datastore:"-"`
}

func (m *Legacy) Reset()         { *m = Legacy{} }
func (m *Legacy) String() string { return proto.CompactTextString(m) }
func (*Legacy) ProtoMessage()    {}
func (*Legacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_legacy_8af53888636eff9e, []int{0}
}
func (m *Legacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Legacy.Unmarshal(m, b)
}
func (m *Legacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Legacy.Marshal(b, m, deterministic)
}
func (dst *Legacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Legacy.Merge(dst, src)
}
func (m *Legacy) XXX_Size() int {
	return xxx_messageInfo_Legacy.Size(m)
}
func (m *Legacy) XXX_DiscardUnknown() {
	xxx_messageInfo_Legacy.DiscardUnknown(m)
}

var xxx_messageInfo_Legacy proto.InternalMessageInfo

func (m *Legacy) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func init() {
	proto.RegisterType((*Legacy)(nil), "api_v1.Legacy")
}

func init() { proto.RegisterFile("legacy.proto", fileDescriptor_legacy_8af53888636eff9e) }

var fileDescriptor_legacy_8af53888636eff9e = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x49, 0x4d, 0x4f,
	0x4c, 0xae, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2c, 0xc8, 0x8c, 0x2f, 0x33,
	0x54, 0x52, 0xe0, 0x62, 0xf3, 0x01, 0x8b, 0x0b, 0x89, 0x71, 0xb1, 0x15, 0xe7, 0x97, 0x16, 0x25,
	0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x41, 0x79, 0x49, 0x6c, 0x60, 0x0d, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x2c, 0xc1, 0xa8, 0x40, 0x00, 0x00, 0x00,
}
